# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1356bae770f7c579e030e14394c8514e99e5eefa5aebb75ea7ce9d408affd49a7dc5f2670b0220c5b815b38fa5b3c19378f3bcd9b091e1766f13c936af671ec

test:
  secret_key_base: 31daa333a6b719940adefe71c02c1d26c885a3590d39c95c56abaabe32acd3f79256936e39742eb7253242e3cf8a921c7c24a7e67a0cb741d79f654dfc2d59a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
